const router = require('express').Router();

const SYSTEM_PROMPT = `You are the official AI Customer Support Assistant for "Bole Animal Feed Processing PLC", located in Bole Michael, Addis Ababa, Ethiopia.
Your goal is to assist farmers, dealers, and customers in English and Amharic. Be friendly, polite, and professional.

Company Info:
- Location: Bole Michael, Addis Ababa, Ethiopia.
- Phone Numbers: +251 939 277 772 / +251 939 377 773 / +251 711 277 771
- Email: info@boleanimalfeed.com
- Working Hours: Monday to Saturday: 8:00 AM – 6:00 PM | Sunday: 9:00 AM – 1:00 PM
- TIN No: 0078912345 | VAT Reg: 98765432
- Shelf Life Guarantee: All bags have a 6-month shelf life guarantee, with clear manufacturing and expiry dates printed on the bags.

Product Catalog & Prices:
1. Layer Super Phase 1 Feed
   - Category: Layer Feed
   - Price: 2,800 ETB per 50kg bag
   - Target: Laying hens aged 18–45 weeks.
   - Protein: Min 16.5%, Calcium: Min 3.75%, Fat: Min 5.0%, Fiber: Max 7.0%.
   - Feeding Guide: 110–120g per bird per day.
   - Benefits: High egg production, strong eggshells, balanced nutrition.

2. Layer Super Phase 2 Feed
   - Category: Layer Feed
   - Price: 2,700 ETB per 50kg bag
   - Target: Laying hens aged 46+ weeks (late laying stage).
   - Protein: Min 15.5%, Calcium: Min 4.0%.
   - Benefits: Sustains egg production, superior eggshell quality in late stages.

3. Broiler Starter Feed
   - Category: Broiler Feed
   - Price: 3,100 ETB per 50kg bag
   - Target: Broiler chicks aged 0–3 weeks.
   - Protein: Min 22.0%, Calcium: Min 1.0%.
   - Feeding Guide: Feed ad libitum (free choice).
   - Benefits: Rapid early growth, strong immune system.

4. Broiler Finisher Feed
   - Category: Broiler Feed
   - Price: 2,950 ETB per 50kg bag
   - Target: Broilers aged 4–7 weeks (until market weight).
   - Protein: Min 19.0%, Calcium: Min 0.9%.
   - Benefits: Maximum weight gain, optimal feed conversion ratio.

5. Dairy Cattle Feed
   - Category: Dairy Feed
   - Price: 2,200 ETB per 50kg bag
   - Target: Lactating dairy cows.
   - Protein: Min 14.0%, Fat: Min 3.5%, Fiber: Max 12.0%.
   - Feeding Guide: Feed 2–4kg per 10L of milk produced, supplement with roughage.
   - Benefits: Maximizes milk yield, supports reproductive health.

How to Place Orders:
- Customers can place orders directly on the website by clicking "Order Now" on any product, filling in their name, phone number, and choosing:
  1. Delivery: Delivered to their farm (delivery fee calculated based on location).
  2. Pickup: Free pickup directly from our factory in Bole Michael, Addis Ababa.
- Payment Methods: Cash on delivery/pickup, Telebirr (we provide a QR code at checkout), CBE bank transfer, or direct bank wire. After paying, customers should enter their transaction reference code on the checkout form.

How to Track Orders:
- After placing an order, customers get an 8-character reference code (e.g., BOLE-0005). They can enter this on the "Track Order" page to see live status updates.

Language Guidelines:
- If the user writes in Amharic, respond politely in Amharic. If they write in English, respond in English.
- Keep answers concise, helpful, and directly related to Bole Animal Feed. Do not answer questions unrelated to the business or animal nutrition. If asked about unrelated things, politely redirect them to your services.`;

// Helper to generate realistic mock templates when GEMINI_API_KEY is not set
function getMockWriteContent(templateType, prompt, tone, lang, details = {}) {
  const isAmharic = lang === 'am';
  
  if (templateType === 'feed_schedule') {
    const animal = details.animal || (isAmharic ? 'የእንቁላል ዶሮዎች' : 'Layers');
    const size = details.size || '500';
    if (isAmharic) {
      return `የአመጋገብ መመሪያ እና የጊዜ ሰሌዳ (በቦሌ እንስሳት መኖ የተዘጋጀ)
--------------------------------------------------
የእንስሳ አይነት: ${animal}
የእንስሳቱ ብዛት: ${size}
የጽሑፍ ዘይቤ: ${tone}

ሳምንታዊ የአመጋገብ ሰንጠረዥ (መመሪያ)፦
1. ሳምንት 1-3 (Broiler Starter / Layer Starter)
   - ዕለታዊ የመኖ መጠን በራስ: 15-20 ግራም
   - ጥቅም: ፈጣን እድገትና የበሽታ መከላከያ አቅም መገንባት።
   - ማሳሰቢያ: ንጹህ ውሃ ሁልጊዜ መገኘት አለበት።

2. ሳምንት 4-8 (Grower Feed)
   - ዕለታዊ የመኖ መጠን በራስ: 40-50 ግራም
   - ጥቅም: አጥንትና ጡንቻን ለማጠንከር።

3. ሳምንት 9-18 (Developer/Layer Phase 1)
   - ዕለታዊ የመኖ መጠን በራስ: 80-95 ግራም
   - ጥቅም: ለእንቁላል ምርት ዝግጅት።

4. ሳምንት 18+ (Layer Super Phase 1)
   - ዕለታዊ የመኖ መጠን በራስ: 110-120 ግራም
   - ጥቅም: ከፍተኛ የእንቁላል ምርት እና የቅርፊት ጥራት።

ምክር:
- መኖውን በደረቅና ቀዝቃዛ ቦታ ያስቀምጡ። የቦሌ መኖዎች የ6 ወር ጥራት ዋስትና አላቸው።
- ለተጨማሪ ዝርዝር በስልክ ቁጥር +251 939 277 772 ይደውሉልን።`;
    } else {
      return `Feeding Guide & Schedule (Generated by Bole Animal Feed)
--------------------------------------------------
Animal Type: ${animal}
Flock/Herd Size: ${size}
Tone: ${tone}

Weekly Feeding Recommendations:
1. Weeks 1–3 (Broiler Starter / Chick Starter)
   - Daily feed per bird: 15–20g
   - Key Benefit: Rapid early growth and immune support.
   - Guide: Feed ad libitum (free choice). Keep clean water available 24/7.

2. Weeks 4–8 (Grower Feed)
   - Daily feed per bird: 40–50g
   - Key Benefit: Bone structure development and steady body weight gain.

3. Weeks 9–18 (Developer / Pre-Lay Feed)
   - Daily feed per bird: 80–95g
   - Key Benefit: Preparing pullets for active laying stage.

4. Weeks 18+ (Layer Super Phase 1)
   - Daily feed per bird: 110–120g
   - Key Benefit: Optimal egg laying rates and strong eggshell formation.

Tips & Best Practices:
- Always store bags in a dry, cool area off the floor. Bole feeds have a 6-month shelf life guarantee.
- For custom advice, contact our specialists at +251 939 277 772.`;
    }
  }

  if (templateType === 'proposal') {
    const name = details.name || (isAmharic ? 'የተከበሩ ደንበኛ' : 'Valued Partner');
    const company = details.company || (isAmharic ? 'ቦሌ እንስሳት መኖ ማቀናበሪያ' : 'Bole Animal Feed Processing PLC');
    if (isAmharic) {
      return `የንግድ ስምምነት / የሽያጭ ደብዳቤ አብነት
--------------------------------------------------
ለ: ${name}
ከ: ${company}
ጉዳዩ: የእንስሳት መኖ በጅምላ ስለማቅረብ የቀረበ ጥያቄ

ክቡር/ክብርት ሆይ፣

ይህ ደብዳቤ ከቦሌ እንስሳት መኖ ማቀናበሪያ ኃ/የተ/የግ/ማህበር የተጻፈ ሲሆን፣ ለእርሻዎ ወይም ለንግድ ድርጅትዎ ጥራት ያለውና ሳይንሳዊ ቀመሩን የጠበቀ መኖ በቅናሽ ዋጋ በጅምላ ለማቅረብ ያለንን ፍላጎት ለመግለጽ ነው።

ቦሌ እንስሳት መኖ ማቀናበሪያ ከፍተኛ ጥራት ያላቸውን የዶሮ እና የወተት ላም መኖዎችን የሚያመርትና የ6 ወር የጥራት ዋስትና ዋስትና የሚሰጥ ድርጅት ነው። 

የእኛ የጅምላ አቅርቦት ጥቅሞች:
1. ተከታታይነት ያለው የጥራት ቁጥጥር (የላብራቶሪ ምርመራ የተደረገለት)
2. የተመጣጠነ የዋጋ ተመን እና የትራንስፖርት ድጋፍ
3. አስተማማኝ እና ፈጣን አቅርቦት ከቦሌ ሚካኤል ፋብሪካችን

ይህንን ትብብር በተመለከተ በዝርዝር ለመወያየት ዝግጁ ነን። በሚከተሉት ስልኮች ሊያገኙን ይችላሉ: +251 939 277 772።

ከሰላምታ ጋር፣
__________________
የሽያጭና ግብይት ክፍል
ቦሌ እንስሳት መኖ ማቀናበሪያ`;
    } else {
      return `Business Proposal / Sales Letter
--------------------------------------------------
To: ${name}
From: ${company}
Subject: Partnership for High-Quality Animal Feed Supply

Dear ${name},

We are writing to you from Bole Animal Feed Processing PLC, located in Bole Michael, Addis Ababa. We specialize in manufacturing high-yielding, scientifically balanced feed for poultry and dairy operations, and we would love to partner with your farm/business as your primary feed supplier.

Why partner with Bole Animal Feed:
1. Certified formulation with guaranteed minimum crude protein, calcium, and fat contents.
2. 6-month shelf life guarantee on all bags with batch numbers for tracking.
3. Competitive wholesale pricing and flexible logistics/delivery to your location.

We would be pleased to schedule a short call or meeting to discuss a customized supply plan and bulk discounts for your operations. Please let us know your availability or contact us directly at +251 939 277 772.

Sincerely,
__________________
Sales & Partnership Team
Bole Animal Feed Processing PLC`;
    }
  }

  if (templateType === 'complaint') {
    const name = details.name || (isAmharic ? 'የእርሻ ባለቤት' : 'Farmer / Customer');
    if (isAmharic) {
      return `የቅሬታ እና አስተያየት ማቅረቢያ ቅጽ
--------------------------------------------------
ለ: የቦሌ እንስሳት መኖ አስተዳደር
ከ: ${name}
ጉዳዩ: መኖን በተመለከተ የቀረበ አስተያየት / ቅሬታ

ክቡር/ክብርት ሆይ፣

የእኛ እርሻ የቦሌ እንስሳት መኖ ምርቶችን በመጠቀም ላይ ይገኛል። ይህንን ደብዳቤ የምጽፈው በቅርቡ ስለገዛነው መኖ ምርት ያለንን አስተያየት/ቅሬታ ለማሳወቅ ነው።

ዝርዝር ሁኔታ:
- የገዛነው የመኖ አይነት: __________________
- የገዛንበት ቀን/ባች ቁጥር: __________________
- የታየው ችግር/አስተያየት:
  ${prompt || 'እባክዎን ያጋጠመውን ሁኔታ እዚህ ያብራሩ...'}

የቦሌ እንስሳት መኖ ለምርቶቹ ጥራት ትልቅ ትኩረት እንደሚሰጥ ስለምናውቅ፣ ይህንን ጉዳይ አይተው ተገቢውን ማስተካከያ ወይም ምክር እንዲሰጡን በአክብሮት እንጠይቃለን።

ስልክ ቁጥር: __________________
እርሻ ቦታ: __________________

ከሰላምታ ጋር፣
__________________`;
    } else {
      return `Feedback / Issue Notification Letter
--------------------------------------------------
To: Management Team, Bole Animal Feed Processing PLC
From: ${name}
Subject: Feedback / Issue Report regarding Feed Batch

Dear Management Team,

I am writing to share feedback/report an issue regarding a recent purchase of Bole Animal Feed for our farming operations.

Details of the Purchase:
- Feed Product Category: __________________
- Date of Purchase / Batch Code (if available): __________________
- Description of the Observation:
  ${prompt || 'Please explain the issue or feedback in detail here...'}

As we highly value the quality and standard guarantee that Bole Animal Feed offers, we hope your production or technical support team can look into this matter and provide feedback. We would appreciate it if you could contact us to discuss this further.

Contact Phone: __________________
Farm Location: __________________

Sincerely,
__________________`;
    }
  }

  // Custom prompt
  if (isAmharic) {
    return `በ AI የተዘጋጀ ጽሑፍ (ቦሌ እንስሳት መኖ)
--------------------------------------------------
ጭብጥ: ${prompt}
የጽሑፍ ዘይቤ: ${tone}

[ውጤት]፦
ለእርስዎ ጥያቄ የተዘጋጀው ጽሑፍ እዚህ ይገኛል፡
ድርጅታችን ቦሌ እንስሳት መኖ ማቀናበሪያ ጥራቱን የጠበቀ የዶሮ (Layer Super Phase 1/2, Broiler Starter/Finisher) እና የወተት ላም መኖዎችን ያቀርባል።

ስለ እርሻዎ የቀረበው ጥያቄ ምላሽ:
- ${prompt} በሚለው ርዕስ ዙሪያ የእንስሳት ጤና እና የአመጋገብ መመሪያዎችን እንዲከተሉ ይመከራል።

ለበለጠ መረጃ፡
- ስልክ፡ +251 939 277 772 | +251 939 377 773
- አድራሻ፡ ቦሌ ሚካኤል፣ አዲስ አበባ፣ ኢትዮጵያ`;
  } else {
    return `AI Custom Generated Writing (Bole Animal Feed)
--------------------------------------------------
Topic: ${prompt}
Tone: ${tone}

[Generated Output]
Here is the customized response to your prompt regarding "${prompt}":

At Bole Animal Feed Processing PLC, we prioritize scientific precision. For your topic:
"${prompt}"

We advise farmers to ensure adequate feed spacing, dry storage, and timely feeding schedules. Keep in mind that all Bole feed bags are guaranteed for 6 months and undergo laboratory analysis for protein and calcium.

If you require customized feed formulations or direct consulting, feel free to contact us at +251 939 277 772 or visit our factory in Bole Michael, Addis Ababa.`;
  }
}

router.post('/chat', async (req, res) => {
  try {
    const { message, history } = req.body;
    if (!message) return res.status(400).json({ error: 'Message is required' });

    const API_KEY = process.env.GEMINI_API_KEY;
    if (!API_KEY) {
      console.warn('⚠️ GEMINI_API_KEY is not configured. Running in demo mode.');
      return res.json({
        reply: "Hello! Our AI system is currently in demo mode. Please configure GEMINI_API_KEY on the server to chat live. Our office number is +251 939 277 772."
      });
    }

    // Format chat history to match Gemini's structure
    const contents = (history || []).map(msg => ({
      role: msg.sender === 'user' ? 'user' : 'model',
      parts: [{ text: msg.text }]
    }));

    // Add current user message
    contents.push({
      role: 'user',
      parts: [{ text: message }]
    });

    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${API_KEY}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents,
        systemInstruction: {
          parts: [{ text: SYSTEM_PROMPT }]
        },
        generationConfig: {
          temperature: 0.7,
          maxOutputTokens: 500
        }
      })
    });

    const data = await response.json();
    
    if (!response.ok) {
      console.error('Gemini API Error:', data);
      return res.status(502).json({ error: 'Error connecting to AI service' });
    }

    const reply = data.candidates?.[0]?.content?.parts?.[0]?.text || "I'm sorry, I couldn't generate a reply. Please try again.";
    res.json({ reply });
  } catch (error) {
    console.error('AI chat endpoint error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// Route for generating text document
router.post('/write', async (req, res) => {
  try {
    const { prompt, templateType, tone, lang, details } = req.body;
    if (!prompt && templateType === 'custom') {
      return res.status(400).json({ error: 'Description or prompt is required' });
    }

    const API_KEY = process.env.GEMINI_API_KEY;
    if (!API_KEY) {
      console.warn('⚠️ GEMINI_API_KEY is not configured. Running in demo mode for writing.');
      const reply = getMockWriteContent(templateType, prompt, tone, lang, details);
      return res.json({ reply });
    }

    const userPrompt = `
      Template Type: ${templateType}
      Target Language: ${lang === 'am' ? 'Amharic' : 'English'}
      Tone of Writing: ${tone}
      Main Topic/Details provided: ${prompt}
      Additional Metadata: ${JSON.stringify(details || {})}
    `;

    const SYSTEM_WRITE_PROMPT = `You are the AI Writing Assistant for "Bole Animal Feed Processing PLC", Addis Ababa, Ethiopia.
    Generate the requested document based on the template type, topic, tone, language, and details.
    Make your output professionally formatted, clear, structured (using Markdown headings, lists or tables if appropriate), and ready for copying.
    Do NOT include any greetings (like "Sure! Here is the document:") or closing remarks. Return ONLY the document text itself.
    Avoid placeholder tags like [Your Name] or [Insert Date]. Use empty lines or underscores "___________" for signatures.`;

    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${API_KEY}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ role: 'user', parts: [{ text: userPrompt }] }],
        systemInstruction: {
          parts: [{ text: SYSTEM_WRITE_PROMPT }]
        },
        generationConfig: {
          temperature: 0.5,
          maxOutputTokens: 1000
        }
      })
    });

    const data = await response.json();
    
    if (!response.ok) {
      console.error('Gemini API Error:', data);
      return res.status(502).json({ error: 'Error connecting to AI service' });
    }

    const reply = data.candidates?.[0]?.content?.parts?.[0]?.text || "I'm sorry, I couldn't generate the document. Please try again.";
    res.json({ reply });
  } catch (error) {
    console.error('AI write endpoint error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// Route for refining a text document
router.post('/refine', async (req, res) => {
  try {
    const { previousText, instruction, lang, tone } = req.body;
    if (!previousText || !instruction) {
      return res.status(400).json({ error: 'Previous text and instruction are required' });
    }

    const API_KEY = process.env.GEMINI_API_KEY;
    if (!API_KEY) {
      console.warn('⚠️ GEMINI_API_KEY is not configured. Running in demo mode for refinement.');
      // Demo refinement: append instruction or mock edit
      const prefix = lang === 'am' ? '\n\n[የተስተካከለ እትም በ AI]፦\n' : '\n\n[AI Refinement Update]:\n';
      const instructionText = lang === 'am' ? `ማስተካከያ የተደረገበት: ${instruction}` : `Adjusted according to: "${instruction}"`;
      return res.json({ reply: previousText + prefix + instructionText });
    }

    const userPrompt = `
      Original Document:
      """
      ${previousText}
      """

      Refinement Instruction:
      "${instruction}"

      Desired Language: ${lang === 'am' ? 'Amharic' : 'English'}
      Desired Tone: ${tone || 'professional'}
    `;

    const SYSTEM_REFINE_PROMPT = `You are the AI Writing Assistant for "Bole Animal Feed Processing PLC".
    You are given a previously generated document and a user's instruction to refine, edit, format, or translate it.
    Apply the requested adjustment precisely while keeping the format clean and professional.
    Do NOT include any greetings or commentary. Output ONLY the updated document.`;

    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${API_KEY}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ role: 'user', parts: [{ text: userPrompt }] }],
        systemInstruction: {
          parts: [{ text: SYSTEM_REFINE_PROMPT }]
        },
        generationConfig: {
          temperature: 0.5,
          maxOutputTokens: 1000
        }
      })
    });

    const data = await response.json();
    
    if (!response.ok) {
      console.error('Gemini API Error:', data);
      return res.status(502).json({ error: 'Error connecting to AI service' });
    }

    const reply = data.candidates?.[0]?.content?.parts?.[0]?.text || previousText;
    res.json({ reply });
  } catch (error) {
    console.error('AI refine endpoint error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

module.exports = router;
